dependencies:
- name: angular-io-quickstart
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- name: golang-jx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: microtrader
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
